name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: go build .
        working-directory: src
      - run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - run: ls -R ~/go
      - run: ~/go/bin/fyne package -os darwin -icon Icon-192.png
        working-directory: src

      - run: ls
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: test.app
